version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: estoque_e_vendas_postgres

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:

    build: .
    container_name: estoque_e_vendas_fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}

volumes:
  postgres_data: